//alerts, modals
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_MODAL = 'SET_MODAL';
export const REMOVE_MODAL = 'REMOVE_MODAL';

//User login, logout, registration, deactivation
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const USERDATA_LOADED = 'USERDATA_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_DATALOAD_STARTED = 'USER_DATALOAD_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';


export const BOOKS_LOADING_STARTED = 'BOOKS_LOADING_STARTED';
export const BOOKS_LOADING_ERROR ='BOOKS_LOADING_ERROR';
export const BOOKS_LOADED = 'BOOKS_LOADED';
export const BOOK_ADDED = 'BOOK_ADDED';
export const BOOK_EDITED = 'BOOK_EDITED';
export const BOOK_ERROR = 'BOOK_ERROR';
export const CLEAR_BOOKS = 'CLEAR_BOOKS';
export const BOOK_NEW_RECORD_FIELD = 'BOOK_NEW_RECORD_FIELD';

export const AUTHORS_LOADING_STARTED = 'AUTHORS_LOADING_STARTED';
export const AUTHORS_LOADING_ERROR = 'AUTHORS_LOADING_ERROR';
export const AUTHORS_LOADED = 'AUTHORS_LOADED';
export const AUTHOR_ADDED = 'AUTHOR_ADDED';
export const AUTHOR_ERROR = 'AUTHOR_ERROR';
export const AUTHOR_NEW_RECORD_FIELD = 'AUTHOR_NEW_RECORD_FIELD';
export const CLEAR_AUTHORS = 'CLEAR_AUTHORS';


//Miscellaneous
export const CLEAR_STATE = 'CLEAR_STATE';

